### ISSUE TITLE
mongo indexes

### ISSUE THREAD

**Issue by oprogramador** [webcaetano/mongo-mysql#3]
MongoDB queries are much faster with indexes (a query on a many millions documents collection with indexes can take less than 1 second but with no indexes many hours or even longer)

So let's compare select queries with indexes as well (MySQL has also indexes).

Could you do it?
Or can I open a PR?

**Comment by webcaetano** [comment]
@oprogramador i'm quite busy at the moment. 
Feel free to submit a PR, i want to see/share the results
